### ISSUE TITLE
Emails are unreadable in dark mode on Windows

### ISSUE THREAD

**Issue by darshanrampatel** [mailpace/templates#1]
I have tested [the previews](https://htmlpreview.github.io/?https://github.com/ohmysmtp/templates/blob/main/dist/welcome.html) on the below configurations (using dark mode in Windows). Note: this also happens when I use my own (local) .html file.

**Windows 10 Pro 1803**

- Google Chrome Version 94.0.4606.61 (Official Build) (64-bit)
- Mozilla Firefox 92.0.1 (64-bit)

**Windows 10 Pro 21H1**

- Google Chrome Version 94.0.4606.61 (Official Build) (64-bit)
- Microsoft Edge Version 95.0.1020.5 (Official build) dev (64-bit)

Screenshot:

![image](https://user-images.githubusercontent.com/14162899/135068793-4f5bea68-34d6-4a7b-9e4d-6880a8689d67.png)

**Comment by paul-oms** [comment]
Thanks @darshanrampatel - I've fixed the issue now, feel free to retest. 

It was caused by line breaks in the class attribute for some specific class names, and in the production configuration these were concatenated together without a space in between. I am not sure entirely why the line breaks were not replaced with a space as this is what should have happened.

**Comment by darshanrampatel** [comment]
@paul-oms thanks - they look much better now!
